CREATE TABLE Metadata (
	Package_Name varchar(180) not null binary primary key,
	Time bigint not null,
	Name varchar(100),
	Download bigint,
	Rating float,
	Rating_Num bigint,
	Five_Star bigint,
	Four_Star bigint,
	Three_Star bigint,
	Two_Star bigint,
	One_Star bigint,
	Category varchar(40),
	Tag varchar(120),
	Edition varchar(30),
	Price varchar(20),
	Update_Time bigint,
	Developer varchar(60),
	Description varchar(5000),
	Release_Note varchar(1500),
	Similar_Apps text
);
